### ISSUE TITLE
闪退!

### ISSUE THREAD

**Issue by ndcc5** [ymyguang/Noss_balance_notify#1]
C:\Noss_balance_notify-master>python banlance.py
[Initial response] fsfu35y7:[{"tick":"noss","balance":40}]
[Initial response] 3s3q5f20:[{"tick":"noss","balance":30}]
[Initial response] dsel48d7:[{"tick":"noss","balance":80}]
[Initial response] vq4vhgcn:[{"tick":"noss","balance":130}]
[Initial response] zs4s90mw:[{"tick":"noss","balance":50}]
Getting balance have encounter error. None
Getting balance have encounter error. None
Getting balance have encounter error. None
Getting balance have encounter error. None
Getting balance have encounter error. None

**Comment by ymyguang** [comment]
收到，已排查出问题，明天修复，感谢关注

**Comment by ymyguang** [comment]
先确认一下，是否是最新的代码？最新的代码为闪退做了一些修复。@ndcc5

**Comment by ndcc5** [comment]
如何更新到最新？我看py文件还是原来的日期

**Comment by ndcc5** [comment]
提个建议，增加一个自定义节点别名字段，现在显示的是钱包地址后几位，很乱。让日志显示钱包地址别名就好了，比如node01，node02 一看就知道是哪台机器出的块、、
